// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCE8I4xIYIfRk-dVhq9Lg021orOu5Uxv7U',
    appId: '1:532885379007:web:62aab2a06dcdb4373ff30a',
    messagingSenderId: '532885379007',
    projectId: 'fyp-game-64095',
    authDomain: 'fyp-game-64095.firebaseapp.com',
    databaseURL: 'https://fyp-game-64095-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fyp-game-64095.appspot.com',
    measurementId: 'G-GHG0VSV5L5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBJgjm9RmAEeukJEOrvzxfrXEvoQbJ5I4',
    appId: '1:532885379007:android:998db0a786ee943a3ff30a',
    messagingSenderId: '532885379007',
    projectId: 'fyp-game-64095',
    databaseURL: 'https://fyp-game-64095-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fyp-game-64095.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVeeOG7qI14uy7rNSJP4BgNS7dVUiKdLo',
    appId: '1:532885379007:ios:a0550f687e9a23513ff30a',
    messagingSenderId: '532885379007',
    projectId: 'fyp-game-64095',
    databaseURL: 'https://fyp-game-64095-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fyp-game-64095.appspot.com',
    iosBundleId: 'com.example.fyp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVeeOG7qI14uy7rNSJP4BgNS7dVUiKdLo',
    appId: '1:532885379007:ios:a0550f687e9a23513ff30a',
    messagingSenderId: '532885379007',
    projectId: 'fyp-game-64095',
    databaseURL: 'https://fyp-game-64095-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fyp-game-64095.appspot.com',
    iosBundleId: 'com.example.fyp2',
  );
}
